### ISSUE TITLE
Vault client error unable to find ca.pem

### ISSUE THREAD

**Issue by nvpnathan** [innovia/kubernetes-mutation-webhook-vault-secrets#1]
I can start an alpine pod and do it manually
/ # curl --header "X-Vault-Token: $TOKEN" -s -k  https://vault.vballin.com:8200/v1/secret/my-app | jq -r .data
{
  "AWS_SECRET_ACCESS_KEY": "sssshhhhIAMSecret"
}

`kubectl logs default-5cc84d6b5f-6t55p`
```
time="2019-11-21T16:30:44Z" level=info msg="Logging into Vault Kubernetes backend using the role: tester"
time="2019-11-21T16:30:44Z" level=fatal msg="Failed to create vault client: error encountered setting up default configuration: lstat /etc/tls/ca.pem: no such file or directory"
```

Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets
  template:
    metadata:
      labels:
        app: hello-secrets
      annotations:
        vault.security/enabled: "true"
        vault.security/vault-addr: "https://vault.example.com:8200"
        vault.security/vault-role: "tester"
        vault.security/vault-path: "secret/my-app"
        vault.security/vault-tls-secret-name: "vault-tls"
    spec:
      serviceAccountName: tester
      containers:
      - name: alpine
        image: alpine
        command:
          - "sh"
          - "-c"
          - "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"
        env:
        - name:  AWS_SECRET_ACCESS_KEY
          value: vault:AWS_SECRET_ACCESS_KEY
```
